---
title: Fruity Knitting 013
author: infuerno
date: '2023-06-05'
slug: fruity-knitting-013
categories: []
tags: [jogging, knitting-in-the-round, fair-isle, steeking]
---

[YouTube](https://www.youtube.com/watch?v=MaaHTytQddY) | [Programme notes](https://fruityknitting.com/2016/09/13/dingo-dyeworks-and-other-australian-delights-ep-13/)

## Under Construction
* Firebird jumper - jogging happens when you are knitting in the round and knitting stripes with different colours
* Alice Starmor tends to start her rows under the arm, where you won't see this change. BUT Andrea started her rows in the middle of the front!
* People in Wales will notice the difference. There are lots of knitters there and they will see it go hmm thats hand knitted and they'll come and investigate you!
* Deliberation over set in sleeves OR drop shoulder sleeves. For Andrea she would definitely do set in sleeves, but for Andrew he can get away with drop shoulder. Normally drop shoulder would be stepped a bit, but with fair isle it would go straigh across and the front and back grafted on completely straight. 
* Description of how Andrea is steeking the sleeves, but suggests Alice Starmor's book to learn all about steeking

## Knitters of the World
* Lady from Brogo, South East Australia - must have been really near where we stopped that time on the road down from Sydney to Melbourne

## KAL
* Montage videos
## Feature

* Petah from Dingo Dyeworks in Perth - mainly Australian Merino which is super soft, in lots of colours inspired by the flora and fauna of Australia. She did used to do a video blog, but seems they have all been taken down.
