baseurl: https://knit.frny.uk/public/
languageCode: en-gb
title: Slip Slip Knit
theme: "hugo-xmin"
googleAnalytics: ''
disqusShortname: ''

ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
footnotereturnlinkcontents: "↩"
permalinks:
  note: /note/:slug/
  post: /post/:slug/
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Projects
      url: /project/
      weight: 2
    - name: Categories
      url: "/categories/"
      weight: 3
    - name: Tags
      url: "/tags/"
      weight: 4
    - name: GitHub
      url: https://github.com/infuerno/frny.uk
    - name: Twitter
      url: https://twitter.com/clairefurney
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  footer: "&copy; [Claire Furney](https://knit.frny.uk) 2023 -- {Year}"
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2
  goldmark:
    renderer:
      unsafe: yes
privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false


