---
title: Fruity Knitting 006
author: infuerno
date: '2023-05-29'
slug: fruity-knitting-006
categories: []
tags: [blocking, kitchener, ]
---

[YouTube](https://www.youtube.com/watch?v=S30h6EVAgHg) | [Programme notes](https://fruityknitting.com/2016/05/31/grafting-your-knitting-and-a-german-yarn-festival-episode-6/)

## Bring and Brag
* Andrew's hermione socks - couldn't find any sock blockers in Germany, so ironed them instead
* Andrea's Softyak Rowan Marie Wallin's Norbu - used kitchener stitch to join the reknitting sleeves back to the main garment
 - for socks it is ok to do it pretty tight on the toes
 - but for joining parts of garments, its better to do it a bit loose and then pull it a bit tighter to match the tension
 - description of how to secure the knitting above and below before cutting it in half
 - short video of the whole process - Andrea will do a more in depth tutorial on this

## KAL
* Andrew - first garment KAL - with sleeves, for adults - June to October 2016
* Andrea - big project Fair Isle KAL - no hats, gloves or cowls - could do a shawl / throw (see Alice Starmor - has a steek)
  - https://www.pinterest.co.uk/pin/189573465545328535/
  - https://www.pinterest.co.uk/pin/189573465545327375/
  - https://www.pinterest.co.uk/pin/189573465542900728/
## Knitters of the World

## Under Construction
* Marie Wallin - Lovage - Fair Isle project - Andrea promises to do a tutorial on her 2 handed knitting technique.

## Feature
* Wool festival in Aschaffenburg, Bavaria
* Natural Dyer Margit Hofmann of Alte Künste (Ancient Arts) - https://www.altekuenste.eu/



