---
title: Fruity Knitting 007
author: infuerno
date: '2023-05-30'
slug: fruity-knitting-007
categories: []
tags: [fair-isle, swatching, two-handed-fair-isle]
---

[YouTube](https://www.youtube.com/watch?v=b-dyDqzFqHc) | [Programme notes](https://fruityknitting.com/2016/06/20/philosophers-wool-knitting-is-love/)

## Under Construction
* Marie Wallin - Lovage - Rowan Fine Tweed
  - stocking stitch stiches are slightly wider than longer
  - fair isle stitches tend to be tighter because of the floats which are carried behind, tends to be closer to a square
  - most patterns suggest you go UP a needle size - need to get the width correct (so it doesn't get pulled into a tight band) e.g. Andrea went up from 2.75mm to 3mm 
  - hard to get BOTH rows and stitches correct when doing a swatch - always go for the stitch count and then do more / less rows
  - for Fair Isle, carefully work out where you can add or subtract extra rows - even 32 rows compared with the patterns 31 rows will be a 1cm difference on the overall length - so its IMPORTANT!
  - ALSO knitting back and forth gauge is different to a knitting in the round gauge BECAUSE when you knit in the round, you only knit and people's knit guage (tighter) tends to be different than their purl guage (looser)
  - swatch for Fair Isle needs to be knit knit knit, so need to somehow to this 

## Knitters of the World
* Steven Self - From Austin Texas, immaculate garments

## From the Archives
* Andrew's wearing Guido from Rowan, yarn is Rowan Purelife Revive - being discontinued - buy it now
  - interesting sounding stitch knit one, slip one, and then on the way back knit the ones you slipped - different coloured wools then merge into each other somewhat

## Feature
* Ann and Eugene Borgeous - The Philopher's Wool company


